In [1]:
import sys
import os

sys.path.append(os.path.dirname(os.getcwd()))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Load Data and initial EDA

In [2]:
df = pd.read_csv("../data/IMDB_Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [5]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
from src.preprocessing import clean_text

df = clean_text(df)

df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

#### Encode Sentiment

In [7]:
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})

In [8]:
df

                                                  review  sentiment
0      one of the other reviewers has mentioned that ...          1
1      a wonderful little production the filming tech...          1
2      i thought this was a wonderful way to spend ti...          1
3      basically theres a family where a little boy j...          0
4      petter matteis love in the time of money is a ...          1
...                                                  ...        ...
49995  i thought this movie did a down right good job...          1
49996  bad plot bad dialogue bad acting idiotic direc...          0
49997  i am a catholic taught in parochial elementary...          0
49998  im going to have to disagree with the previous...          0
49999  no one expects the star trek movies to be high...          0

[50000 rows x 2 columns]